/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...path]': typeof import('./src/pages/[...path].vue')['default']
    '[id]': typeof import('./src/pages/categories/[id].vue')['default']
    AllView: typeof import('./src/pages/AllView.vue')['default']
    Browse: typeof import('./src/pages/Browse.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ContentFeed: typeof import('./src/pages/ContentFeed.vue')['default']
    Download: typeof import('./src/pages/Download.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Error404: typeof import('./src/pages/error404.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InstallApp: typeof import('./src/pages/InstallApp.vue')['default']
    MusicController: typeof import('./src/components/MusicController.vue')['default']
    MusicTab: typeof import('./src/pages/musicTab.vue')['default']
    MusicView: typeof import('./src/pages/MusicView.vue')['default']
    MyFooter: typeof import('./src/components/MyFooter.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    MyTab: typeof import('./src/components/MyTab.vue')['default']
    NotFoundView: typeof import('./src/pages/NotFoundView.vue')['default']
    Notifications: typeof import('./src/pages/Notifications.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    Podcast: typeof import('./src/pages/Podcast.vue')['default']
    PodcastsView: typeof import('./src/pages/PodcastsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/pages/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SonglistTab: typeof import('./src/components/SonglistTab.vue')['default']
  }
}
