/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/AllView': RouteRecordInfo<'/AllView', '/AllView', Record<never, never>, Record<never, never>>,
    '/categories/[id]': RouteRecordInfo<'/categories/[id]', '/categories/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Download': RouteRecordInfo<'/Download', '/Download', Record<never, never>, Record<never, never>>,
    '/MusicView': RouteRecordInfo<'/MusicView', '/MusicView', Record<never, never>, Record<never, never>>,
    '/Notifications': RouteRecordInfo<'/Notifications', '/Notifications', Record<never, never>, Record<never, never>>,
    '/Podcast': RouteRecordInfo<'/Podcast', '/Podcast', Record<never, never>, Record<never, never>>,
    '/Search': RouteRecordInfo<'/Search', '/Search', Record<never, never>, Record<never, never>>,
  }
}
